language: php

php:
  # aliased to a recent 7.x version
  - 7.2

before_script:
  - cat /etc/ssl/openssl.cnf
  - composer install
  
script: vendor/bin/phpunit tests --colors --coverage-clover=coverage.xml